const fruit = [
    
    {
        name:"Apple",
        logo:"./",
        price:"3",
    },
    {
        name:"apple",
        logo:"sdjskjdnc",
        price:"1",
    },
    {
        name:"banana",
        logo:"sdskdcsjd",
        price:"2",
    },
    {
        name:"orange",
        logo:"oikjhgv",
        price:"3",
    },
    {
        name:"orange",
        logo:"oikjhgv",
        price:"3",
    },
    {
        name:"apple",
        logo:"sdjskjdnc",
        price:"1",
    },
    {
        name:"banana",
        logo:"sdskdcsjd",
        price:"2",
    },
    {
        name:"orange",
        logo:"oikjhgv",
        price:"3",
    },
    {
        name:"orange",
        logo:"oikjhgv",
        price:"3",
    },
    {
        name:"apple",
        logo:"sdjskjdnc",
        price:"1",
    },
    {
        name:"banana",
        logo:"sdskdcsjd",
        price:"2",
    },
    {
        name:"orange",
        logo:"oikjhgv",
        price:"3",
    },
    {
        name:"orange",
        logo:"oikjhgv",
        price:"3",
    },
    {
        name:"apple",
        logo:"sdjskjdnc",
        price:"1",
    },
    {
        name:"banana",
        logo:"sdskdcsjd",
        price:"2",
    },
    {
        name:"orange",
        logo:"oikjhgv",
        price:"3",
    },
]
export default fruit;
